// Mocks generated by Mockito 5.4.6 from annotations
// in musicbud_flutter/test/blocs/discover/discover_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:musicbud_flutter/domain/repositories/discover_repository.dart'
    as _i3;
import 'package:musicbud_flutter/models/album.dart' as _i11;
import 'package:musicbud_flutter/models/artist.dart' as _i7;
import 'package:musicbud_flutter/models/common_anime.dart' as _i9;
import 'package:musicbud_flutter/models/common_manga.dart' as _i10;
import 'package:musicbud_flutter/models/discover_item.dart' as _i5;
import 'package:musicbud_flutter/models/genre.dart' as _i8;
import 'package:musicbud_flutter/models/track.dart' as _i6;
import 'package:musicbud_flutter/models/user_profile.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DiscoverRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoverRepository extends _i1.Mock
    implements _i3.DiscoverRepository {
  MockDiscoverRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<String>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<_i5.DiscoverItem>> getDiscoverItems(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscoverItems,
          [category],
        ),
        returnValue:
            _i4.Future<List<_i5.DiscoverItem>>.value(<_i5.DiscoverItem>[]),
      ) as _i4.Future<List<_i5.DiscoverItem>>);

  @override
  _i4.Future<void> trackInteraction({
    required String? itemId,
    required String? type,
    required String? action,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackInteraction,
          [],
          {
            #itemId: itemId,
            #type: type,
            #action: action,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.UserProfile> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserProfile>);

  @override
  _i4.Future<void> setProfile(_i2.UserProfileUpdateRequest? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #setProfile,
          [profile],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateLikes(Map<String, dynamic>? likes) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLikes,
          [likes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Track>> getTopTracks() => (super.noSuchMethod(
        Invocation.method(
          #getTopTracks,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Track>>.value(<_i6.Track>[]),
      ) as _i4.Future<List<_i6.Track>>);

  @override
  _i4.Future<List<_i7.Artist>> getTopArtists() => (super.noSuchMethod(
        Invocation.method(
          #getTopArtists,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Artist>>.value(<_i7.Artist>[]),
      ) as _i4.Future<List<_i7.Artist>>);

  @override
  _i4.Future<List<_i8.Genre>> getTopGenres() => (super.noSuchMethod(
        Invocation.method(
          #getTopGenres,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Genre>>.value(<_i8.Genre>[]),
      ) as _i4.Future<List<_i8.Genre>>);

  @override
  _i4.Future<List<_i9.CommonAnime>> getTopAnime() => (super.noSuchMethod(
        Invocation.method(
          #getTopAnime,
          [],
        ),
        returnValue:
            _i4.Future<List<_i9.CommonAnime>>.value(<_i9.CommonAnime>[]),
      ) as _i4.Future<List<_i9.CommonAnime>>);

  @override
  _i4.Future<List<_i10.CommonManga>> getTopManga() => (super.noSuchMethod(
        Invocation.method(
          #getTopManga,
          [],
        ),
        returnValue:
            _i4.Future<List<_i10.CommonManga>>.value(<_i10.CommonManga>[]),
      ) as _i4.Future<List<_i10.CommonManga>>);

  @override
  _i4.Future<List<_i6.Track>> getLikedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getLikedTracks,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Track>>.value(<_i6.Track>[]),
      ) as _i4.Future<List<_i6.Track>>);

  @override
  _i4.Future<List<_i7.Artist>> getLikedArtists() => (super.noSuchMethod(
        Invocation.method(
          #getLikedArtists,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Artist>>.value(<_i7.Artist>[]),
      ) as _i4.Future<List<_i7.Artist>>);

  @override
  _i4.Future<List<_i8.Genre>> getLikedGenres() => (super.noSuchMethod(
        Invocation.method(
          #getLikedGenres,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Genre>>.value(<_i8.Genre>[]),
      ) as _i4.Future<List<_i8.Genre>>);

  @override
  _i4.Future<List<_i11.Album>> getLikedAlbums() => (super.noSuchMethod(
        Invocation.method(
          #getLikedAlbums,
          [],
        ),
        returnValue: _i4.Future<List<_i11.Album>>.value(<_i11.Album>[]),
      ) as _i4.Future<List<_i11.Album>>);

  @override
  _i4.Future<List<_i6.Track>> getPlayedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracks,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Track>>.value(<_i6.Track>[]),
      ) as _i4.Future<List<_i6.Track>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getFeaturedArtists() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeaturedArtists,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getTrendingTracks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendingTracks,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getNewReleases() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNewReleases,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getDiscoverActions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscoverActions,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<String>> getDiscoverCategories() => (super.noSuchMethod(
        Invocation.method(
          #getDiscoverCategories,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);
}
