// Mocks generated by Mockito 5.4.6 from annotations
// in musicbud_flutter/test/blocs/bud_matching/bud_matching_bloc_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:musicbud_flutter/domain/repositories/bud_matching_repository.dart'
    as _i4;
import 'package:musicbud_flutter/models/bud_profile.dart' as _i2;
import 'package:musicbud_flutter/models/bud_search_result.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBudProfile_0 extends _i1.SmartFake implements _i2.BudProfile {
  _FakeBudProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBudSearchResult_1 extends _i1.SmartFake
    implements _i3.BudSearchResult {
  _FakeBudSearchResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BudMatchingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudMatchingRepository extends _i1.Mock
    implements _i4.BudMatchingRepository {
  MockBudMatchingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.BudProfile> fetchBudProfile(String? budId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBudProfile,
          [budId],
        ),
        returnValue: _i5.Future<_i2.BudProfile>.value(_FakeBudProfile_0(
          this,
          Invocation.method(
            #fetchBudProfile,
            [budId],
          ),
        )),
      ) as _i5.Future<_i2.BudProfile>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByTopArtists() => (super.noSuchMethod(
        Invocation.method(
          #findBudsByTopArtists,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByTopArtists,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByTopTracks() => (super.noSuchMethod(
        Invocation.method(
          #findBudsByTopTracks,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByTopTracks,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByTopGenres() => (super.noSuchMethod(
        Invocation.method(
          #findBudsByTopGenres,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByTopGenres,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByTopAnime() => (super.noSuchMethod(
        Invocation.method(
          #findBudsByTopAnime,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByTopAnime,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByTopManga() => (super.noSuchMethod(
        Invocation.method(
          #findBudsByTopManga,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByTopManga,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByLikedArtists() =>
      (super.noSuchMethod(
        Invocation.method(
          #findBudsByLikedArtists,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByLikedArtists,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByLikedTracks() =>
      (super.noSuchMethod(
        Invocation.method(
          #findBudsByLikedTracks,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByLikedTracks,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByLikedGenres() =>
      (super.noSuchMethod(
        Invocation.method(
          #findBudsByLikedGenres,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByLikedGenres,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByLikedAlbums() =>
      (super.noSuchMethod(
        Invocation.method(
          #findBudsByLikedAlbums,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByLikedAlbums,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByLikedAio() => (super.noSuchMethod(
        Invocation.method(
          #findBudsByLikedAio,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByLikedAio,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByPlayedTracks() =>
      (super.noSuchMethod(
        Invocation.method(
          #findBudsByPlayedTracks,
          [],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByPlayedTracks,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByArtist(String? artistId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findBudsByArtist,
          [artistId],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByArtist,
            [artistId],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByTrack(String? trackId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findBudsByTrack,
          [trackId],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByTrack,
            [trackId],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);

  @override
  _i5.Future<_i3.BudSearchResult> findBudsByGenre(String? genreId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findBudsByGenre,
          [genreId],
        ),
        returnValue:
            _i5.Future<_i3.BudSearchResult>.value(_FakeBudSearchResult_1(
          this,
          Invocation.method(
            #findBudsByGenre,
            [genreId],
          ),
        )),
      ) as _i5.Future<_i3.BudSearchResult>);
}
