// Mocks generated by Mockito 5.4.6 from annotations
// in musicbud_flutter/test/blocs/chat/chat_bloc_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:musicbud_flutter/domain/repositories/chat_repository.dart'
    as _i6;
import 'package:musicbud_flutter/models/channel.dart' as _i4;
import 'package:musicbud_flutter/models/chat.dart' as _i2;
import 'package:musicbud_flutter/models/chat_message.dart' as _i3;
import 'package:musicbud_flutter/models/message.dart' as _i5;
import 'package:musicbud_flutter/models/user_profile.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChat_0 extends _i1.SmartFake implements _i2.Chat {
  _FakeChat_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatMessage_1 extends _i1.SmartFake implements _i3.ChatMessage {
  _FakeChatMessage_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannel_2 extends _i1.SmartFake implements _i4.Channel {
  _FakeChannel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessage_3 extends _i1.SmartFake implements _i5.Message {
  _FakeMessage_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i6.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i2.Chat>> getChats() => (super.noSuchMethod(
        Invocation.method(
          #getChats,
          [],
        ),
        returnValue: _i7.Future<List<_i2.Chat>>.value(<_i2.Chat>[]),
      ) as _i7.Future<List<_i2.Chat>>);

  @override
  _i7.Future<_i2.Chat> getChatByUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getChatByUserId,
          [userId],
        ),
        returnValue: _i7.Future<_i2.Chat>.value(_FakeChat_0(
          this,
          Invocation.method(
            #getChatByUserId,
            [userId],
          ),
        )),
      ) as _i7.Future<_i2.Chat>);

  @override
  _i7.Future<List<_i3.ChatMessage>> getChatMessages(
    String? chatId, {
    int? limit,
    String? before,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatMessages,
          [chatId],
          {
            #limit: limit,
            #before: before,
          },
        ),
        returnValue:
            _i7.Future<List<_i3.ChatMessage>>.value(<_i3.ChatMessage>[]),
      ) as _i7.Future<List<_i3.ChatMessage>>);

  @override
  _i7.Future<_i3.ChatMessage> sendDirectMessage(
    String? chatId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendDirectMessage,
          [
            chatId,
            content,
          ],
        ),
        returnValue: _i7.Future<_i3.ChatMessage>.value(_FakeChatMessage_1(
          this,
          Invocation.method(
            #sendDirectMessage,
            [
              chatId,
              content,
            ],
          ),
        )),
      ) as _i7.Future<_i3.ChatMessage>);

  @override
  _i7.Future<void> markAsRead(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [chatId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markChatAsRead(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #markChatAsRead,
          [chatId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteChat(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #deleteChat,
          [chatId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> archiveChat(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #archiveChat,
          [chatId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.Channel>> getChannels() => (super.noSuchMethod(
        Invocation.method(
          #getChannels,
          [],
        ),
        returnValue: _i7.Future<List<_i4.Channel>>.value(<_i4.Channel>[]),
      ) as _i7.Future<List<_i4.Channel>>);

  @override
  _i7.Future<_i4.Channel> getChannel(String? channelId) => (super.noSuchMethod(
        Invocation.method(
          #getChannel,
          [channelId],
        ),
        returnValue: _i7.Future<_i4.Channel>.value(_FakeChannel_2(
          this,
          Invocation.method(
            #getChannel,
            [channelId],
          ),
        )),
      ) as _i7.Future<_i4.Channel>);

  @override
  _i7.Future<_i4.Channel> createChannel(
    String? name,
    String? description, {
    bool? isPrivate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createChannel,
          [
            name,
            description,
          ],
          {#isPrivate: isPrivate},
        ),
        returnValue: _i7.Future<_i4.Channel>.value(_FakeChannel_2(
          this,
          Invocation.method(
            #createChannel,
            [
              name,
              description,
            ],
            {#isPrivate: isPrivate},
          ),
        )),
      ) as _i7.Future<_i4.Channel>);

  @override
  _i7.Future<void> updateChannel(
    String? channelId,
    String? name,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChannel,
          [
            channelId,
            name,
            description,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteChannel(String? channelId) => (super.noSuchMethod(
        Invocation.method(
          #deleteChannel,
          [channelId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.Message>> getChannelMessages(
    String? channelId, {
    int? limit,
    String? before,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelMessages,
          [channelId],
          {
            #limit: limit,
            #before: before,
          },
        ),
        returnValue: _i7.Future<List<_i5.Message>>.value(<_i5.Message>[]),
      ) as _i7.Future<List<_i5.Message>>);

  @override
  _i7.Future<_i5.Message> sendChannelMessage(
    String? channelId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendChannelMessage,
          [
            channelId,
            content,
          ],
        ),
        returnValue: _i7.Future<_i5.Message>.value(_FakeMessage_3(
          this,
          Invocation.method(
            #sendChannelMessage,
            [
              channelId,
              content,
            ],
          ),
        )),
      ) as _i7.Future<_i5.Message>);

  @override
  _i7.Future<void> joinChannel(String? channelId) => (super.noSuchMethod(
        Invocation.method(
          #joinChannel,
          [channelId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> leaveChannel(String? channelId) => (super.noSuchMethod(
        Invocation.method(
          #leaveChannel,
          [channelId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.UserProfile>> getChannelMembers(String? channelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelMembers,
          [channelId],
        ),
        returnValue:
            _i7.Future<List<_i8.UserProfile>>.value(<_i8.UserProfile>[]),
      ) as _i7.Future<List<_i8.UserProfile>>);

  @override
  _i7.Future<void> addChannelMember(
    String? channelId,
    String? username,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addChannelMember,
          [
            channelId,
            username,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> getChannelStatistics(String? channelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelStatistics,
          [channelId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<bool> isChannelAdmin(String? channelId) => (super.noSuchMethod(
        Invocation.method(
          #isChannelAdmin,
          [channelId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> addModerator(
    String? channelId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addModerator,
          [
            channelId,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeModerator(
    String? channelId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeModerator,
          [
            channelId,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> makeAdmin(
    String? channelId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeAdmin,
          [
            channelId,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeAdmin(
    String? channelId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAdmin,
          [
            channelId,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> kickUser(
    String? channelId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #kickUser,
          [
            channelId,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> blockUser(
    String? channelId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [
            channelId,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> unblockUser(
    String? channelId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [
            channelId,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.UserProfile>> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.UserProfile>>.value(<_i8.UserProfile>[]),
      ) as _i7.Future<List<_i8.UserProfile>>);

  @override
  _i7.Future<Map<String, dynamic>> getChannelUsers(String? channelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelUsers,
          [channelId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> deleteMessage(
    String? channelId,
    String? messageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [
            channelId,
            messageId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> requestJoinChannel(String? channelId) => (super.noSuchMethod(
        Invocation.method(
          #requestJoinChannel,
          [channelId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> getChannelDetails(String? channelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelDetails,
          [channelId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getChannelDashboardData(String? channelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelDashboardData,
          [channelId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, bool>> checkChannelRoles(String? channelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkChannelRoles,
          [channelId],
        ),
        returnValue: _i7.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i7.Future<Map<String, bool>>);

  @override
  _i7.Future<void> performAdminAction(
    String? channelId,
    String? action,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #performAdminAction,
          [
            channelId,
            action,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getChannelInvitations(
          String? channelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelInvitations,
          [channelId],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getChannelBlockedUsers(
          String? channelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChannelBlockedUsers,
          [channelId],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getUserInvitations(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserInvitations,
          [userId],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<_i5.Message>> getUserMessages(
    String? userId, {
    int? limit,
    String? before,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserMessages,
          [userId],
          {
            #limit: limit,
            #before: before,
          },
        ),
        returnValue: _i7.Future<List<_i5.Message>>.value(<_i5.Message>[]),
      ) as _i7.Future<List<_i5.Message>>);

  @override
  _i7.Future<_i5.Message> sendUserMessage(
    String? userId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendUserMessage,
          [
            userId,
            content,
          ],
        ),
        returnValue: _i7.Future<_i5.Message>.value(_FakeMessage_3(
          this,
          Invocation.method(
            #sendUserMessage,
            [
              userId,
              content,
            ],
          ),
        )),
      ) as _i7.Future<_i5.Message>);

  @override
  _i7.Future<void> sendMessage({
    required String? channelId,
    required String? message,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #channelId: channelId,
            #message: message,
            #userId: userId,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<dynamic>> getMessages({
    required String? channelId,
    int? limit,
    String? beforeId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [],
          {
            #channelId: channelId,
            #limit: limit,
            #beforeId: beforeId,
          },
        ),
        returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i7.Future<List<dynamic>>);

  @override
  _i7.Future<void> sendInvitation(
    String? channelId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendInvitation,
          [
            channelId,
            userId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> acceptInvitation(String? invitationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptInvitation,
          [invitationId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> declineInvitation(String? invitationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #declineInvitation,
          [invitationId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
