// Mocks generated by Mockito 5.4.6 from annotations
// in musicbud_flutter/test/blocs/profile/profile_bloc_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:musicbud_flutter/domain/repositories/content_repository.dart'
    as _i12;
import 'package:musicbud_flutter/domain/repositories/user_profile_repository.dart'
    as _i10;
import 'package:musicbud_flutter/domain/repositories/user_repository.dart'
    as _i14;
import 'package:musicbud_flutter/models/album.dart' as _i5;
import 'package:musicbud_flutter/models/artist.dart' as _i4;
import 'package:musicbud_flutter/models/common_anime.dart' as _i7;
import 'package:musicbud_flutter/models/common_manga.dart' as _i8;
import 'package:musicbud_flutter/models/genre.dart' as _i6;
import 'package:musicbud_flutter/models/parent_user.dart' as _i9;
import 'package:musicbud_flutter/models/spotify_device.dart' as _i13;
import 'package:musicbud_flutter/models/track.dart' as _i3;
import 'package:musicbud_flutter/models/user_profile.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTrack_1 extends _i1.SmartFake implements _i3.Track {
  _FakeTrack_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArtist_2 extends _i1.SmartFake implements _i4.Artist {
  _FakeArtist_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlbum_3 extends _i1.SmartFake implements _i5.Album {
  _FakeAlbum_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenre_4 extends _i1.SmartFake implements _i6.Genre {
  _FakeGenre_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommonAnime_5 extends _i1.SmartFake implements _i7.CommonAnime {
  _FakeCommonAnime_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommonManga_6 extends _i1.SmartFake implements _i8.CommonManga {
  _FakeCommonManga_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeParentUser_7 extends _i1.SmartFake implements _i9.ParentUser {
  _FakeParentUser_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRepository extends _i1.Mock
    implements _i10.UserProfileRepository {
  MockUserProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.UserProfile> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i11.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getUserProfile,
            [userId],
          ),
        )),
      ) as _i11.Future<_i2.UserProfile>);

  @override
  _i11.Future<_i2.UserProfile> getMyProfile({
    String? service,
    String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyProfile,
          [],
          {
            #service: service,
            #token: token,
          },
        ),
        returnValue: _i11.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getMyProfile,
            [],
            {
              #service: service,
              #token: token,
            },
          ),
        )),
      ) as _i11.Future<_i2.UserProfile>);

  @override
  _i11.Future<_i2.UserProfile> updateProfile(
          _i2.UserProfileUpdateRequest? updateRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [updateRequest],
        ),
        returnValue: _i11.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #updateProfile,
            [updateRequest],
          ),
        )),
      ) as _i11.Future<_i2.UserProfile>);

  @override
  _i11.Future<void> updateLikes(Map<String, dynamic>? likesData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLikes,
          [likesData],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<dynamic>> getUserLikedContent(
    String? contentType,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLikedContent,
          [
            contentType,
            userId,
          ],
        ),
        returnValue: _i11.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i11.Future<List<dynamic>>);

  @override
  _i11.Future<List<dynamic>> getMyLikedContent(String? contentType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyLikedContent,
          [contentType],
        ),
        returnValue: _i11.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i11.Future<List<dynamic>>);

  @override
  _i11.Future<List<dynamic>> getUserTopContent(
    String? contentType,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserTopContent,
          [
            contentType,
            userId,
          ],
        ),
        returnValue: _i11.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i11.Future<List<dynamic>>);

  @override
  _i11.Future<List<dynamic>> getMyTopContent(String? contentType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyTopContent,
          [contentType],
        ),
        returnValue: _i11.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i11.Future<List<dynamic>>);

  @override
  _i11.Future<List<dynamic>> getUserPlayedTracks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPlayedTracks,
          [userId],
        ),
        returnValue: _i11.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i11.Future<List<dynamic>>);

  @override
  _i11.Future<List<dynamic>> getMyPlayedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getMyPlayedTracks,
          [],
        ),
        returnValue: _i11.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i11.Future<List<dynamic>>);
}

/// A class which mocks [ContentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentRepository extends _i1.Mock implements _i12.ContentRepository {
  MockContentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i3.Track>> getPlayedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracks,
          [],
        ),
        returnValue: _i11.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i11.Future<List<_i3.Track>>);

  @override
  _i11.Future<List<_i3.Track>> getPlayedTracksWithLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracksWithLocation,
          [],
        ),
        returnValue: _i11.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i11.Future<List<_i3.Track>>);

  @override
  _i11.Future<List<_i13.SpotifyDevice>> getSpotifyDevices() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpotifyDevices,
          [],
        ),
        returnValue:
            _i11.Future<List<_i13.SpotifyDevice>>.value(<_i13.SpotifyDevice>[]),
      ) as _i11.Future<List<_i13.SpotifyDevice>>);

  @override
  _i11.Future<void> controlSpotifyPlayback(
    String? command,
    String? deviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #controlSpotifyPlayback,
          [
            command,
            deviceId,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setSpotifyVolume(
    String? deviceId,
    int? volume,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSpotifyVolume,
          [
            deviceId,
            volume,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveTrackLocation(
    String? trackId,
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTrackLocation,
          [
            trackId,
            latitude,
            longitude,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> playTrack(
    String? trackId,
    String? deviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #playTrack,
          [
            trackId,
            deviceId,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> playTrackWithLocation(
    String? trackId,
    String? trackName,
    double? latitude,
    double? longitude, [
    String? deviceId,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playTrackWithLocation,
          [
            trackId,
            trackName,
            latitude,
            longitude,
            deviceId,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> savePlayedTrack(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #savePlayedTrack,
          [trackId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i3.Track>> getPopularTracks() => (super.noSuchMethod(
        Invocation.method(
          #getPopularTracks,
          [],
        ),
        returnValue: _i11.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i11.Future<List<_i3.Track>>);

  @override
  _i11.Future<List<_i4.Artist>> getPopularArtists() => (super.noSuchMethod(
        Invocation.method(
          #getPopularArtists,
          [],
        ),
        returnValue: _i11.Future<List<_i4.Artist>>.value(<_i4.Artist>[]),
      ) as _i11.Future<List<_i4.Artist>>);

  @override
  _i11.Future<List<_i5.Album>> getPopularAlbums() => (super.noSuchMethod(
        Invocation.method(
          #getPopularAlbums,
          [],
        ),
        returnValue: _i11.Future<List<_i5.Album>>.value(<_i5.Album>[]),
      ) as _i11.Future<List<_i5.Album>>);

  @override
  _i11.Future<List<_i7.CommonAnime>> getPopularAnime() => (super.noSuchMethod(
        Invocation.method(
          #getPopularAnime,
          [],
        ),
        returnValue:
            _i11.Future<List<_i7.CommonAnime>>.value(<_i7.CommonAnime>[]),
      ) as _i11.Future<List<_i7.CommonAnime>>);

  @override
  _i11.Future<List<_i8.CommonManga>> getPopularManga() => (super.noSuchMethod(
        Invocation.method(
          #getPopularManga,
          [],
        ),
        returnValue:
            _i11.Future<List<_i8.CommonManga>>.value(<_i8.CommonManga>[]),
      ) as _i11.Future<List<_i8.CommonManga>>);

  @override
  _i11.Future<List<_i3.Track>> getTopTracks() => (super.noSuchMethod(
        Invocation.method(
          #getTopTracks,
          [],
        ),
        returnValue: _i11.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i11.Future<List<_i3.Track>>);

  @override
  _i11.Future<List<_i4.Artist>> getTopArtists() => (super.noSuchMethod(
        Invocation.method(
          #getTopArtists,
          [],
        ),
        returnValue: _i11.Future<List<_i4.Artist>>.value(<_i4.Artist>[]),
      ) as _i11.Future<List<_i4.Artist>>);

  @override
  _i11.Future<List<_i6.Genre>> getTopGenres() => (super.noSuchMethod(
        Invocation.method(
          #getTopGenres,
          [],
        ),
        returnValue: _i11.Future<List<_i6.Genre>>.value(<_i6.Genre>[]),
      ) as _i11.Future<List<_i6.Genre>>);

  @override
  _i11.Future<List<_i7.CommonAnime>> getTopAnime() => (super.noSuchMethod(
        Invocation.method(
          #getTopAnime,
          [],
        ),
        returnValue:
            _i11.Future<List<_i7.CommonAnime>>.value(<_i7.CommonAnime>[]),
      ) as _i11.Future<List<_i7.CommonAnime>>);

  @override
  _i11.Future<List<_i8.CommonManga>> getTopManga() => (super.noSuchMethod(
        Invocation.method(
          #getTopManga,
          [],
        ),
        returnValue:
            _i11.Future<List<_i8.CommonManga>>.value(<_i8.CommonManga>[]),
      ) as _i11.Future<List<_i8.CommonManga>>);

  @override
  _i11.Future<List<_i3.Track>> getLikedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getLikedTracks,
          [],
        ),
        returnValue: _i11.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i11.Future<List<_i3.Track>>);

  @override
  _i11.Future<List<_i4.Artist>> getLikedArtists() => (super.noSuchMethod(
        Invocation.method(
          #getLikedArtists,
          [],
        ),
        returnValue: _i11.Future<List<_i4.Artist>>.value(<_i4.Artist>[]),
      ) as _i11.Future<List<_i4.Artist>>);

  @override
  _i11.Future<List<_i5.Album>> getLikedAlbums() => (super.noSuchMethod(
        Invocation.method(
          #getLikedAlbums,
          [],
        ),
        returnValue: _i11.Future<List<_i5.Album>>.value(<_i5.Album>[]),
      ) as _i11.Future<List<_i5.Album>>);

  @override
  _i11.Future<List<_i6.Genre>> getLikedGenres() => (super.noSuchMethod(
        Invocation.method(
          #getLikedGenres,
          [],
        ),
        returnValue: _i11.Future<List<_i6.Genre>>.value(<_i6.Genre>[]),
      ) as _i11.Future<List<_i6.Genre>>);

  @override
  _i11.Future<void> likeTrack(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #likeTrack,
          [trackId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> unlikeTrack(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeTrack,
          [trackId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> likeArtist(String? artistId) => (super.noSuchMethod(
        Invocation.method(
          #likeArtist,
          [artistId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> unlikeArtist(String? artistId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeArtist,
          [artistId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> likeAlbum(String? albumId) => (super.noSuchMethod(
        Invocation.method(
          #likeAlbum,
          [albumId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> unlikeAlbum(String? albumId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeAlbum,
          [albumId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> likeGenre(String? genreId) => (super.noSuchMethod(
        Invocation.method(
          #likeGenre,
          [genreId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> unlikeGenre(String? genreId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeGenre,
          [genreId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> likeAnime(String? animeId) => (super.noSuchMethod(
        Invocation.method(
          #likeAnime,
          [animeId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> unlikeAnime(String? animeId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeAnime,
          [animeId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> likeManga(String? mangaId) => (super.noSuchMethod(
        Invocation.method(
          #likeManga,
          [mangaId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> unlikeManga(String? mangaId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeManga,
          [mangaId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i3.Track>> searchTracks(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTracks,
          [query],
        ),
        returnValue: _i11.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i11.Future<List<_i3.Track>>);

  @override
  _i11.Future<List<_i4.Artist>> searchArtists(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchArtists,
          [query],
        ),
        returnValue: _i11.Future<List<_i4.Artist>>.value(<_i4.Artist>[]),
      ) as _i11.Future<List<_i4.Artist>>);

  @override
  _i11.Future<List<_i5.Album>> searchAlbums(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchAlbums,
          [query],
        ),
        returnValue: _i11.Future<List<_i5.Album>>.value(<_i5.Album>[]),
      ) as _i11.Future<List<_i5.Album>>);

  @override
  _i11.Future<List<_i6.Genre>> searchGenres(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchGenres,
          [query],
        ),
        returnValue: _i11.Future<List<_i6.Genre>>.value(<_i6.Genre>[]),
      ) as _i11.Future<List<_i6.Genre>>);

  @override
  _i11.Future<List<_i7.CommonAnime>> searchAnime(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchAnime,
          [query],
        ),
        returnValue:
            _i11.Future<List<_i7.CommonAnime>>.value(<_i7.CommonAnime>[]),
      ) as _i11.Future<List<_i7.CommonAnime>>);

  @override
  _i11.Future<List<_i8.CommonManga>> searchManga(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchManga,
          [query],
        ),
        returnValue:
            _i11.Future<List<_i8.CommonManga>>.value(<_i8.CommonManga>[]),
      ) as _i11.Future<List<_i8.CommonManga>>);

  @override
  _i11.Future<_i3.Track> getTrackDetails(String? trackId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrackDetails,
          [trackId],
        ),
        returnValue: _i11.Future<_i3.Track>.value(_FakeTrack_1(
          this,
          Invocation.method(
            #getTrackDetails,
            [trackId],
          ),
        )),
      ) as _i11.Future<_i3.Track>);

  @override
  _i11.Future<_i4.Artist> getArtistDetails(String? artistId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArtistDetails,
          [artistId],
        ),
        returnValue: _i11.Future<_i4.Artist>.value(_FakeArtist_2(
          this,
          Invocation.method(
            #getArtistDetails,
            [artistId],
          ),
        )),
      ) as _i11.Future<_i4.Artist>);

  @override
  _i11.Future<_i5.Album> getAlbumDetails(String? albumId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAlbumDetails,
          [albumId],
        ),
        returnValue: _i11.Future<_i5.Album>.value(_FakeAlbum_3(
          this,
          Invocation.method(
            #getAlbumDetails,
            [albumId],
          ),
        )),
      ) as _i11.Future<_i5.Album>);

  @override
  _i11.Future<_i6.Genre> getGenreDetails(String? genreId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGenreDetails,
          [genreId],
        ),
        returnValue: _i11.Future<_i6.Genre>.value(_FakeGenre_4(
          this,
          Invocation.method(
            #getGenreDetails,
            [genreId],
          ),
        )),
      ) as _i11.Future<_i6.Genre>);

  @override
  _i11.Future<_i7.CommonAnime> getAnimeDetails(String? animeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnimeDetails,
          [animeId],
        ),
        returnValue: _i11.Future<_i7.CommonAnime>.value(_FakeCommonAnime_5(
          this,
          Invocation.method(
            #getAnimeDetails,
            [animeId],
          ),
        )),
      ) as _i11.Future<_i7.CommonAnime>);

  @override
  _i11.Future<_i8.CommonManga> getMangaDetails(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMangaDetails,
          [mangaId],
        ),
        returnValue: _i11.Future<_i8.CommonManga>.value(_FakeCommonManga_6(
          this,
          Invocation.method(
            #getMangaDetails,
            [mangaId],
          ),
        )),
      ) as _i11.Future<_i8.CommonManga>);

  @override
  _i11.Future<List<dynamic>> getTopItems(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopItems,
          [category],
        ),
        returnValue: _i11.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i11.Future<List<dynamic>>);

  @override
  _i11.Future<List<dynamic>> getLikedItems(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedItems,
          [category],
        ),
        returnValue: _i11.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i11.Future<List<dynamic>>);

  @override
  _i11.Future<void> toggleTrackLike(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #toggleTrackLike,
          [trackId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> toggleArtistLike(String? artistId) => (super.noSuchMethod(
        Invocation.method(
          #toggleArtistLike,
          [artistId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> toggleAlbumLike(String? albumId) => (super.noSuchMethod(
        Invocation.method(
          #toggleAlbumLike,
          [albumId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> toggleGenreLike(String? genreId) => (super.noSuchMethod(
        Invocation.method(
          #toggleGenreLike,
          [genreId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> toggleAnimeLike(String? animeId) => (super.noSuchMethod(
        Invocation.method(
          #toggleAnimeLike,
          [animeId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> toggleMangaLike(String? mangaId) => (super.noSuchMethod(
        Invocation.method(
          #toggleMangaLike,
          [mangaId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> updateLikes(
    String? type,
    String? id,
    bool? isLiked,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLikes,
          [
            type,
            id,
            isLiked,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> toggleLike(
    String? id,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLike,
          [
            id,
            type,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> playTrackOnService(
    String? trackIdentifier, {
    String? service,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playTrackOnService,
          [trackIdentifier],
          {#service: service},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> createPlaylist({
    required String? name,
    String? description,
    bool? isPrivate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPlaylist,
          [],
          {
            #name: name,
            #description: description,
            #isPrivate: isPrivate,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> deletePlaylist(String? playlistId) => (super.noSuchMethod(
        Invocation.method(
          #deletePlaylist,
          [playlistId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> updatePlaylist(
    String? playlistId, {
    String? name,
    String? description,
    bool? isPublic,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlaylist,
          [playlistId],
          {
            #name: name,
            #description: description,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> addTrackToPlaylist(
    String? playlistId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTrackToPlaylist,
          [
            playlistId,
            trackId,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> removeTrackFromPlaylist(
    String? playlistId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTrackFromPlaylist,
          [
            playlistId,
            trackId,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i14.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.UserProfile> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i11.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i11.Future<_i2.UserProfile>);

  @override
  _i11.Future<_i9.ParentUser> getParentUser() => (super.noSuchMethod(
        Invocation.method(
          #getParentUser,
          [],
        ),
        returnValue: _i11.Future<_i9.ParentUser>.value(_FakeParentUser_7(
          this,
          Invocation.method(
            #getParentUser,
            [],
          ),
        )),
      ) as _i11.Future<_i9.ParentUser>);

  @override
  _i11.Future<_i2.UserProfile> getBudProfile(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudProfile,
          [username],
        ),
        returnValue: _i11.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getBudProfile,
            [username],
          ),
        )),
      ) as _i11.Future<_i2.UserProfile>);

  @override
  _i11.Future<void> updateMyProfile(_i2.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMyProfile,
          [profile],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> updateMyLikes() => (super.noSuchMethod(
        Invocation.method(
          #updateMyLikes,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> updateUserProfile(
    String? userId,
    Map<String, dynamic>? profileData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [
            userId,
            profileData,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i4.Artist>> getLikedArtists() => (super.noSuchMethod(
        Invocation.method(
          #getLikedArtists,
          [],
        ),
        returnValue: _i11.Future<List<_i4.Artist>>.value(<_i4.Artist>[]),
      ) as _i11.Future<List<_i4.Artist>>);

  @override
  _i11.Future<List<_i3.Track>> getLikedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getLikedTracks,
          [],
        ),
        returnValue: _i11.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i11.Future<List<_i3.Track>>);

  @override
  _i11.Future<List<_i5.Album>> getLikedAlbums() => (super.noSuchMethod(
        Invocation.method(
          #getLikedAlbums,
          [],
        ),
        returnValue: _i11.Future<List<_i5.Album>>.value(<_i5.Album>[]),
      ) as _i11.Future<List<_i5.Album>>);

  @override
  _i11.Future<List<_i6.Genre>> getLikedGenres() => (super.noSuchMethod(
        Invocation.method(
          #getLikedGenres,
          [],
        ),
        returnValue: _i11.Future<List<_i6.Genre>>.value(<_i6.Genre>[]),
      ) as _i11.Future<List<_i6.Genre>>);

  @override
  _i11.Future<List<_i4.Artist>> getTopArtists() => (super.noSuchMethod(
        Invocation.method(
          #getTopArtists,
          [],
        ),
        returnValue: _i11.Future<List<_i4.Artist>>.value(<_i4.Artist>[]),
      ) as _i11.Future<List<_i4.Artist>>);

  @override
  _i11.Future<List<_i3.Track>> getTopTracks() => (super.noSuchMethod(
        Invocation.method(
          #getTopTracks,
          [],
        ),
        returnValue: _i11.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i11.Future<List<_i3.Track>>);

  @override
  _i11.Future<List<_i6.Genre>> getTopGenres() => (super.noSuchMethod(
        Invocation.method(
          #getTopGenres,
          [],
        ),
        returnValue: _i11.Future<List<_i6.Genre>>.value(<_i6.Genre>[]),
      ) as _i11.Future<List<_i6.Genre>>);

  @override
  _i11.Future<List<_i7.CommonAnime>> getTopAnime() => (super.noSuchMethod(
        Invocation.method(
          #getTopAnime,
          [],
        ),
        returnValue:
            _i11.Future<List<_i7.CommonAnime>>.value(<_i7.CommonAnime>[]),
      ) as _i11.Future<List<_i7.CommonAnime>>);

  @override
  _i11.Future<List<_i8.CommonManga>> getTopManga() => (super.noSuchMethod(
        Invocation.method(
          #getTopManga,
          [],
        ),
        returnValue:
            _i11.Future<List<_i8.CommonManga>>.value(<_i8.CommonManga>[]),
      ) as _i11.Future<List<_i8.CommonManga>>);

  @override
  _i11.Future<String> getSpotifyAuthUrl() => (super.noSuchMethod(
        Invocation.method(
          #getSpotifyAuthUrl,
          [],
        ),
        returnValue: _i11.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getSpotifyAuthUrl,
            [],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<void> connectSpotify(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectSpotify,
          [code],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> disconnectSpotify() => (super.noSuchMethod(
        Invocation.method(
          #disconnectSpotify,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<String> getYTMusicAuthUrl() => (super.noSuchMethod(
        Invocation.method(
          #getYTMusicAuthUrl,
          [],
        ),
        returnValue: _i11.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getYTMusicAuthUrl,
            [],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<void> connectYTMusic(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectYTMusic,
          [code],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> disconnectYTMusic() => (super.noSuchMethod(
        Invocation.method(
          #disconnectYTMusic,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<String> getMALAuthUrl() => (super.noSuchMethod(
        Invocation.method(
          #getMALAuthUrl,
          [],
        ),
        returnValue: _i11.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getMALAuthUrl,
            [],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<void> connectMAL(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectMAL,
          [code],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> disconnectMAL() => (super.noSuchMethod(
        Invocation.method(
          #disconnectMAL,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<String> getLastFMAuthUrl() => (super.noSuchMethod(
        Invocation.method(
          #getLastFMAuthUrl,
          [],
        ),
        returnValue: _i11.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #getLastFMAuthUrl,
            [],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<void> connectLastFM(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectLastFM,
          [code],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> disconnectLastFM() => (super.noSuchMethod(
        Invocation.method(
          #disconnectLastFM,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveLocation(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocation,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i3.Track>> getPlayedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracks,
          [],
        ),
        returnValue: _i11.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i11.Future<List<_i3.Track>>);

  @override
  _i11.Future<List<_i3.Track>> getPlayedTracksWithLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracksWithLocation,
          [],
        ),
        returnValue: _i11.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i11.Future<List<_i3.Track>>);

  @override
  _i11.Future<List<_i3.Track>> getCurrentlyPlayedTracks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentlyPlayedTracks,
          [],
        ),
        returnValue: _i11.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i11.Future<List<_i3.Track>>);

  @override
  _i11.Future<void> likeSong(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #likeSong,
          [songId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> unlikeSong(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeSong,
          [songId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> banUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #banUser,
          [userId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> unbanUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #unbanUser,
          [userId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<List<_i2.UserProfile>> getBannedUsers() => (super.noSuchMethod(
        Invocation.method(
          #getBannedUsers,
          [],
        ),
        returnValue:
            _i11.Future<List<_i2.UserProfile>>.value(<_i2.UserProfile>[]),
      ) as _i11.Future<List<_i2.UserProfile>>);

  @override
  void updateToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #updateToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );
}
