// Mocks generated by Mockito 5.4.6 from annotations
// in musicbud_flutter/test/data/data_sources/auth_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:musicbud_flutter/data/network/dio_client.dart' as _i3;
import 'package:musicbud_flutter/models/endpoint.dart' as _i6;
import 'package:musicbud_flutter/services/endpoint_config_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i3.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i4.Future<_i2.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {#queryParameters: queryParameters},
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #get,
            [path],
            {#queryParameters: queryParameters},
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> post(
    String? path, {
    dynamic data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {#data: data},
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #post,
            [path],
            {#data: data},
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> put(
    String? path, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {#data: data},
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #put,
            [path],
            {#data: data},
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> delete(
    String? path, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {#queryParameters: queryParameters},
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #delete,
            [path],
            {#queryParameters: queryParameters},
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  void addInterceptor(_i2.Interceptor? interceptor) => super.noSuchMethod(
        Invocation.method(
          #addInterceptor,
          [interceptor],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateBaseUrl(String? baseUrl) => super.noSuchMethod(
        Invocation.method(
          #updateBaseUrl,
          [baseUrl],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateHeaders(Map<String, dynamic>? headers) => super.noSuchMethod(
        Invocation.method(
          #updateHeaders,
          [headers],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EndpointConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEndpointConfigService extends _i1.Mock
    implements _i5.EndpointConfigService {
  MockEndpointConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i6.Endpoint> getAllEndpoints() => (super.noSuchMethod(
        Invocation.method(
          #getAllEndpoints,
          [],
        ),
        returnValue: <_i6.Endpoint>[],
      ) as List<_i6.Endpoint>);

  @override
  _i6.Endpoint? getEndpointByName(String? name) =>
      (super.noSuchMethod(Invocation.method(
        #getEndpointByName,
        [name],
      )) as _i6.Endpoint?);

  @override
  String? getEndpointUrl(
    String? name,
    String? baseUrl,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getEndpointUrl,
        [
          name,
          baseUrl,
        ],
      )) as String?);

  @override
  String? getEndpointMethod(String? name) =>
      (super.noSuchMethod(Invocation.method(
        #getEndpointMethod,
        [name],
      )) as String?);

  @override
  Map<String, String>? getEndpointInfo(
    String? name,
    String? baseUrl,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getEndpointInfo,
        [
          name,
          baseUrl,
        ],
      )) as Map<String, String>?);

  @override
  bool hasEndpoint(String? name) => (super.noSuchMethod(
        Invocation.method(
          #hasEndpoint,
          [name],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<_i6.Endpoint> getEndpointsByStatus(String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEndpointsByStatus,
          [status],
        ),
        returnValue: <_i6.Endpoint>[],
      ) as List<_i6.Endpoint>);
}
