// Mocks generated by Mockito 5.4.6 from annotations
// in musicbud_flutter/test/widgets/screens/home/dynamic_home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:musicbud_flutter/services/dynamic_config_service.dart' as _i4;
import 'package:musicbud_flutter/services/dynamic_navigation_service.dart'
    as _i8;
import 'package:musicbud_flutter/services/dynamic_theme_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeThemeData_0 extends _i1.SmartFake implements _i2.ThemeData {
  _FakeThemeData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeEdgeInsets_1 extends _i1.SmartFake implements _i2.EdgeInsets {
  _FakeEdgeInsets_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIconData_2 extends _i1.SmartFake implements _i2.IconData {
  _FakeIconData_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_3<T extends _i2.State<_i2.StatefulWidget>>
    extends _i1.SmartFake implements _i2.GlobalKey<T> {
  _FakeGlobalKey_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DynamicConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDynamicConfigService extends _i1.Mock
    implements _i4.DynamicConfigService {
  MockDynamicConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  T get<T>(
    String? key, {
    T? defaultValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValue: _i6.dummyValue<T>(
          this,
          Invocation.method(
            #get,
            [key],
            {#defaultValue: defaultValue},
          ),
        ),
      ) as T);

  @override
  _i5.Future<void> set<T>(
    String? key,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> update(Map<String, dynamic>? newConfig) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [newConfig],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool isFeatureEnabled(String? feature) => (super.noSuchMethod(
        Invocation.method(
          #isFeatureEnabled,
          [feature],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setFeatureEnabled(
    String? feature,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFeatureEnabled,
          [
            feature,
            enabled,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  String getApiEndpoint() => (super.noSuchMethod(
        Invocation.method(
          #getApiEndpoint,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getApiEndpoint,
            [],
          ),
        ),
      ) as String);

  @override
  String getTheme() => (super.noSuchMethod(
        Invocation.method(
          #getTheme,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTheme,
            [],
          ),
        ),
      ) as String);

  @override
  _i5.Future<void> setTheme(String? theme) => (super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [theme],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  String getLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getLanguage,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguage,
            [],
          ),
        ),
      ) as String);

  @override
  _i5.Future<void> setLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [language],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool isAnalyticsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isAnalyticsEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> setAnalyticsEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setAnalyticsEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  int getCacheDuration() => (super.noSuchMethod(
        Invocation.method(
          #getCacheDuration,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<void> setCacheDuration(int? duration) => (super.noSuchMethod(
        Invocation.method(
          #setCacheDuration,
          [duration],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  int getTimeout() => (super.noSuchMethod(
        Invocation.method(
          #getTimeout,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<void> setTimeout(int? timeout) => (super.noSuchMethod(
        Invocation.method(
          #setTimeout,
          [timeout],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  int getMaxRetries() => (super.noSuchMethod(
        Invocation.method(
          #getMaxRetries,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<void> setMaxRetries(int? retries) => (super.noSuchMethod(
        Invocation.method(
          #setMaxRetries,
          [retries],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic> getUiConfig() => (super.noSuchMethod(
        Invocation.method(
          #getUiConfig,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> getPrivacyConfig() => (super.noSuchMethod(
        Invocation.method(
          #getPrivacyConfig,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DynamicThemeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDynamicThemeService extends _i1.Mock
    implements _i7.DynamicThemeService {
  MockDynamicThemeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i2.ThemeMode.system,
      ) as _i2.ThemeMode);

  @override
  String get currentThemeName => (super.noSuchMethod(
        Invocation.getter(#currentThemeName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#currentThemeName),
        ),
      ) as String);

  @override
  _i2.ThemeData get lightTheme => (super.noSuchMethod(
        Invocation.getter(#lightTheme),
        returnValue: _FakeThemeData_0(
          this,
          Invocation.getter(#lightTheme),
        ),
      ) as _i2.ThemeData);

  @override
  _i2.ThemeData get darkTheme => (super.noSuchMethod(
        Invocation.getter(#darkTheme),
        returnValue: _FakeThemeData_0(
          this,
          Invocation.getter(#darkTheme),
        ),
      ) as _i2.ThemeData);

  @override
  bool get animationsEnabled => (super.noSuchMethod(
        Invocation.getter(#animationsEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get compactMode => (super.noSuchMethod(
        Invocation.getter(#compactMode),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setThemeMode(_i2.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setPrimaryColor(dynamic color) => (super.noSuchMethod(
        Invocation.method(
          #setPrimaryColor,
          [color],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i2.ThemeData getThemeData(dynamic brightness) => (super.noSuchMethod(
        Invocation.method(
          #getThemeData,
          [brightness],
        ),
        returnValue: _FakeThemeData_0(
          this,
          Invocation.method(
            #getThemeData,
            [brightness],
          ),
        ),
      ) as _i2.ThemeData);

  @override
  _i5.Future<void> setAnimationsEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setAnimationsEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setCompactMode(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setCompactMode,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i2.EdgeInsets getDynamicPadding(_i2.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDynamicPadding,
          [context],
        ),
        returnValue: _FakeEdgeInsets_1(
          this,
          Invocation.method(
            #getDynamicPadding,
            [context],
          ),
        ),
      ) as _i2.EdgeInsets);

  @override
  double getDynamicSpacing(double? baseSpacing) => (super.noSuchMethod(
        Invocation.method(
          #getDynamicSpacing,
          [baseSpacing],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double getDynamicFontSize(double? baseFontSize) => (super.noSuchMethod(
        Invocation.method(
          #getDynamicFontSize,
          [baseFontSize],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i2.ThemeData createResponsiveTheme(_i2.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #createResponsiveTheme,
          [context],
        ),
        returnValue: _FakeThemeData_0(
          this,
          Invocation.method(
            #createResponsiveTheme,
            [context],
          ),
        ),
      ) as _i2.ThemeData);

  @override
  dynamic getThemeAwareColor(
    _i2.BuildContext? context, {
    required dynamic lightColor,
    required dynamic darkColor,
  }) =>
      super.noSuchMethod(Invocation.method(
        #getThemeAwareColor,
        [context],
        {
          #lightColor: lightColor,
          #darkColor: darkColor,
        },
      ));

  @override
  _i2.IconData getThemeAwareIcon(
    _i2.BuildContext? context, {
    required _i2.IconData? lightIcon,
    required _i2.IconData? darkIcon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThemeAwareIcon,
          [context],
          {
            #lightIcon: lightIcon,
            #darkIcon: darkIcon,
          },
        ),
        returnValue: _FakeIconData_2(
          this,
          Invocation.method(
            #getThemeAwareIcon,
            [context],
            {
              #lightIcon: lightIcon,
              #darkIcon: darkIcon,
            },
          ),
        ),
      ) as _i2.IconData);

  @override
  _i5.Future<void> setTheme(_i2.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [mode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DynamicNavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDynamicNavigationService extends _i1.Mock
    implements _i8.DynamicNavigationService {
  MockDynamicNavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GlobalKey<_i2.NavigatorState> get navigatorKey => (super.noSuchMethod(
        Invocation.getter(#navigatorKey),
        returnValue: _FakeGlobalKey_3<_i2.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
      ) as _i2.GlobalKey<_i2.NavigatorState>);

  @override
  Map<String, _i2.WidgetBuilder> get routes => (super.noSuchMethod(
        Invocation.getter(#routes),
        returnValue: <String, _i2.WidgetBuilder>{},
      ) as Map<String, _i2.WidgetBuilder>);

  @override
  List<String> get navigationHistory => (super.noSuchMethod(
        Invocation.getter(#navigationHistory),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addRoute(
    String? name,
    _i2.WidgetBuilder? builder,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addRoute,
          [
            name,
            builder,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeRoute(String? name) => super.noSuchMethod(
        Invocation.method(
          #removeRoute,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> updateRoutes(Map<String, _i2.WidgetBuilder>? newRoutes) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRoutes,
          [newRoutes],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T?> navigateTo<T extends Object?>(
    String? routeName, {
    Object? arguments,
    bool? replace = false,
    bool? clearStack = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #replace: replace,
            #clearStack: clearStack,
          },
        ),
        returnValue: _i5.Future<T?>.value(),
      ) as _i5.Future<T?>);

  @override
  void goBack<T extends Object?>([T? result]) => super.noSuchMethod(
        Invocation.method(
          #goBack,
          [result],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> goBackToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #goBackToPrevious,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearHistory() => super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasRoute(String? routeName) => (super.noSuchMethod(
        Invocation.method(
          #hasRoute,
          [routeName],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> navigateConditionally(
    String? routeName, {
    required bool? condition,
    String? fallbackRoute,
    Object? arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateConditionally,
          [routeName],
          {
            #condition: condition,
            #fallbackRoute: fallbackRoute,
            #arguments: arguments,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> navigateWithFeatureCheck(
    String? routeName, {
    required String? featureFlag,
    String? fallbackRoute,
    Object? arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithFeatureCheck,
          [routeName],
          {
            #featureFlag: featureFlag,
            #fallbackRoute: fallbackRoute,
            #arguments: arguments,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> navigateWithPermissionCheck(
    String? routeName, {
    required String? permission,
    String? fallbackRoute,
    Object? arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithPermissionCheck,
          [routeName],
          {
            #permission: permission,
            #fallbackRoute: fallbackRoute,
            #arguments: arguments,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> navigateWithAnalytics(
    String? routeName, {
    Object? arguments,
    Map<String, dynamic>? analyticsData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithAnalytics,
          [routeName],
          {
            #arguments: arguments,
            #analyticsData: analyticsData,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic> getRouteConfig(String? routeName) => (super.noSuchMethod(
        Invocation.method(
          #getRouteConfig,
          [routeName],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool requiresAuth(String? routeName) => (super.noSuchMethod(
        Invocation.method(
          #requiresAuth,
          [routeName],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool shouldShowBottomNav(String? routeName) => (super.noSuchMethod(
        Invocation.method(
          #shouldShowBottomNav,
          [routeName],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool allowsBack(String? routeName) => (super.noSuchMethod(
        Invocation.method(
          #allowsBack,
          [routeName],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.Route<dynamic>? onGenerateRoute(_i2.RouteSettings? settings) =>
      (super.noSuchMethod(Invocation.method(
        #onGenerateRoute,
        [settings],
      )) as _i2.Route<dynamic>?);
}
