// Mocks generated by Mockito 5.4.6 from annotations
// in musicbud_flutter/test/blocs/settings/settings_bloc_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:musicbud_flutter/domain/repositories/auth_repository.dart'
    as _i6;
import 'package:musicbud_flutter/domain/repositories/settings_repository.dart'
    as _i4;
import 'package:musicbud_flutter/domain/repositories/user_profile_repository.dart'
    as _i8;
import 'package:musicbud_flutter/models/auth_response.dart' as _i2;
import 'package:musicbud_flutter/models/user_profile.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponse_0 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterResponse_1 extends _i1.SmartFake
    implements _i2.RegisterResponse {
  _FakeRegisterResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTokenRefreshResponse_2 extends _i1.SmartFake
    implements _i2.TokenRefreshResponse {
  _FakeTokenRefreshResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_3 extends _i1.SmartFake implements _i3.UserProfile {
  _FakeUserProfile_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i4.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, dynamic>> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> updateNotificationSettings(Map<String, dynamic>? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotificationSettings,
          [settings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updatePrivacySettings(Map<String, dynamic>? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePrivacySettings,
          [settings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTheme(String? theme) => (super.noSuchMethod(
        Invocation.method(
          #updateTheme,
          [theme],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateLanguage(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #updateLanguage,
          [languageCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.LoginResponse> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue: _i5.Future<_i2.LoginResponse>.value(_FakeLoginResponse_0(
          this,
          Invocation.method(
            #login,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.LoginResponse>);

  @override
  _i5.Future<_i2.RegisterResponse> register(
    String? username,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            username,
            email,
            password,
          ],
        ),
        returnValue:
            _i5.Future<_i2.RegisterResponse>.value(_FakeRegisterResponse_1(
          this,
          Invocation.method(
            #register,
            [
              username,
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.RegisterResponse>);

  @override
  _i5.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.TokenRefreshResponse> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i5.Future<_i2.TokenRefreshResponse>.value(
            _FakeTokenRefreshResponse_2(
          this,
          Invocation.method(
            #refreshToken,
            [],
          ),
        )),
      ) as _i5.Future<_i2.TokenRefreshResponse>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getServiceAuthUrl() => (super.noSuchMethod(
        Invocation.method(
          #getServiceAuthUrl,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getServiceAuthUrl,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> getServiceLoginUrl(String? service) => (super.noSuchMethod(
        Invocation.method(
          #getServiceLoginUrl,
          [service],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getServiceLoginUrl,
            [service],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> connectSpotify(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectSpotify,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> connectYTMusic(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectYTMusic,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> connectLastFM(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectLastFM,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> connectMAL(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectMAL,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshSpotifyToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshSpotifyToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshYTMusicToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshYTMusicToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [UserProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRepository extends _i1.Mock
    implements _i8.UserProfileRepository {
  MockUserProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.UserProfile> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_3(
          this,
          Invocation.method(
            #getUserProfile,
            [userId],
          ),
        )),
      ) as _i5.Future<_i3.UserProfile>);

  @override
  _i5.Future<_i3.UserProfile> getMyProfile({
    String? service,
    String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyProfile,
          [],
          {
            #service: service,
            #token: token,
          },
        ),
        returnValue: _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_3(
          this,
          Invocation.method(
            #getMyProfile,
            [],
            {
              #service: service,
              #token: token,
            },
          ),
        )),
      ) as _i5.Future<_i3.UserProfile>);

  @override
  _i5.Future<_i3.UserProfile> updateProfile(
          _i3.UserProfileUpdateRequest? updateRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [updateRequest],
        ),
        returnValue: _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_3(
          this,
          Invocation.method(
            #updateProfile,
            [updateRequest],
          ),
        )),
      ) as _i5.Future<_i3.UserProfile>);

  @override
  _i5.Future<void> updateLikes(Map<String, dynamic>? likesData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLikes,
          [likesData],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<dynamic>> getUserLikedContent(
    String? contentType,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLikedContent,
          [
            contentType,
            userId,
          ],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<List<dynamic>> getMyLikedContent(String? contentType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyLikedContent,
          [contentType],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<List<dynamic>> getUserTopContent(
    String? contentType,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserTopContent,
          [
            contentType,
            userId,
          ],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<List<dynamic>> getMyTopContent(String? contentType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyTopContent,
          [contentType],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<List<dynamic>> getUserPlayedTracks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPlayedTracks,
          [userId],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<List<dynamic>> getMyPlayedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getMyPlayedTracks,
          [],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);
}
