// Mocks generated by Mockito 5.4.6 from annotations
// in musicbud_flutter/test/blocs/user/user_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:musicbud_flutter/domain/repositories/user_repository.dart'
    as _i4;
import 'package:musicbud_flutter/models/album.dart' as _i8;
import 'package:musicbud_flutter/models/artist.dart' as _i6;
import 'package:musicbud_flutter/models/common_anime.dart' as _i10;
import 'package:musicbud_flutter/models/common_manga.dart' as _i11;
import 'package:musicbud_flutter/models/genre.dart' as _i9;
import 'package:musicbud_flutter/models/parent_user.dart' as _i3;
import 'package:musicbud_flutter/models/track.dart' as _i7;
import 'package:musicbud_flutter/models/user_profile.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeParentUser_1 extends _i1.SmartFake implements _i3.ParentUser {
  _FakeParentUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i4.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserProfile> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i5.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i2.UserProfile>);

  @override
  _i5.Future<_i3.ParentUser> getParentUser() => (super.noSuchMethod(
        Invocation.method(
          #getParentUser,
          [],
        ),
        returnValue: _i5.Future<_i3.ParentUser>.value(_FakeParentUser_1(
          this,
          Invocation.method(
            #getParentUser,
            [],
          ),
        )),
      ) as _i5.Future<_i3.ParentUser>);

  @override
  _i5.Future<_i2.UserProfile> getBudProfile(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudProfile,
          [username],
        ),
        returnValue: _i5.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getBudProfile,
            [username],
          ),
        )),
      ) as _i5.Future<_i2.UserProfile>);

  @override
  _i5.Future<void> updateMyProfile(_i2.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMyProfile,
          [profile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateMyLikes() => (super.noSuchMethod(
        Invocation.method(
          #updateMyLikes,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateUserProfile(
    String? userId,
    Map<String, dynamic>? profileData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [
            userId,
            profileData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Artist>> getLikedArtists() => (super.noSuchMethod(
        Invocation.method(
          #getLikedArtists,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Artist>>.value(<_i6.Artist>[]),
      ) as _i5.Future<List<_i6.Artist>>);

  @override
  _i5.Future<List<_i7.Track>> getLikedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getLikedTracks,
          [],
        ),
        returnValue: _i5.Future<List<_i7.Track>>.value(<_i7.Track>[]),
      ) as _i5.Future<List<_i7.Track>>);

  @override
  _i5.Future<List<_i8.Album>> getLikedAlbums() => (super.noSuchMethod(
        Invocation.method(
          #getLikedAlbums,
          [],
        ),
        returnValue: _i5.Future<List<_i8.Album>>.value(<_i8.Album>[]),
      ) as _i5.Future<List<_i8.Album>>);

  @override
  _i5.Future<List<_i9.Genre>> getLikedGenres() => (super.noSuchMethod(
        Invocation.method(
          #getLikedGenres,
          [],
        ),
        returnValue: _i5.Future<List<_i9.Genre>>.value(<_i9.Genre>[]),
      ) as _i5.Future<List<_i9.Genre>>);

  @override
  _i5.Future<List<_i6.Artist>> getTopArtists() => (super.noSuchMethod(
        Invocation.method(
          #getTopArtists,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Artist>>.value(<_i6.Artist>[]),
      ) as _i5.Future<List<_i6.Artist>>);

  @override
  _i5.Future<List<_i7.Track>> getTopTracks() => (super.noSuchMethod(
        Invocation.method(
          #getTopTracks,
          [],
        ),
        returnValue: _i5.Future<List<_i7.Track>>.value(<_i7.Track>[]),
      ) as _i5.Future<List<_i7.Track>>);

  @override
  _i5.Future<List<_i9.Genre>> getTopGenres() => (super.noSuchMethod(
        Invocation.method(
          #getTopGenres,
          [],
        ),
        returnValue: _i5.Future<List<_i9.Genre>>.value(<_i9.Genre>[]),
      ) as _i5.Future<List<_i9.Genre>>);

  @override
  _i5.Future<List<_i10.CommonAnime>> getTopAnime() => (super.noSuchMethod(
        Invocation.method(
          #getTopAnime,
          [],
        ),
        returnValue:
            _i5.Future<List<_i10.CommonAnime>>.value(<_i10.CommonAnime>[]),
      ) as _i5.Future<List<_i10.CommonAnime>>);

  @override
  _i5.Future<List<_i11.CommonManga>> getTopManga() => (super.noSuchMethod(
        Invocation.method(
          #getTopManga,
          [],
        ),
        returnValue:
            _i5.Future<List<_i11.CommonManga>>.value(<_i11.CommonManga>[]),
      ) as _i5.Future<List<_i11.CommonManga>>);

  @override
  _i5.Future<String> getSpotifyAuthUrl() => (super.noSuchMethod(
        Invocation.method(
          #getSpotifyAuthUrl,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getSpotifyAuthUrl,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> connectSpotify(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectSpotify,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disconnectSpotify() => (super.noSuchMethod(
        Invocation.method(
          #disconnectSpotify,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getYTMusicAuthUrl() => (super.noSuchMethod(
        Invocation.method(
          #getYTMusicAuthUrl,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getYTMusicAuthUrl,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> connectYTMusic(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectYTMusic,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disconnectYTMusic() => (super.noSuchMethod(
        Invocation.method(
          #disconnectYTMusic,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getMALAuthUrl() => (super.noSuchMethod(
        Invocation.method(
          #getMALAuthUrl,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getMALAuthUrl,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> connectMAL(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectMAL,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disconnectMAL() => (super.noSuchMethod(
        Invocation.method(
          #disconnectMAL,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getLastFMAuthUrl() => (super.noSuchMethod(
        Invocation.method(
          #getLastFMAuthUrl,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getLastFMAuthUrl,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> connectLastFM(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectLastFM,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disconnectLastFM() => (super.noSuchMethod(
        Invocation.method(
          #disconnectLastFM,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveLocation(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocation,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.Track>> getPlayedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracks,
          [],
        ),
        returnValue: _i5.Future<List<_i7.Track>>.value(<_i7.Track>[]),
      ) as _i5.Future<List<_i7.Track>>);

  @override
  _i5.Future<List<_i7.Track>> getPlayedTracksWithLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracksWithLocation,
          [],
        ),
        returnValue: _i5.Future<List<_i7.Track>>.value(<_i7.Track>[]),
      ) as _i5.Future<List<_i7.Track>>);

  @override
  _i5.Future<List<_i7.Track>> getCurrentlyPlayedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentlyPlayedTracks,
          [],
        ),
        returnValue: _i5.Future<List<_i7.Track>>.value(<_i7.Track>[]),
      ) as _i5.Future<List<_i7.Track>>);

  @override
  _i5.Future<void> likeSong(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #likeSong,
          [songId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unlikeSong(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeSong,
          [songId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> banUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #banUser,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unbanUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #unbanUser,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.UserProfile>> getBannedUsers() => (super.noSuchMethod(
        Invocation.method(
          #getBannedUsers,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.UserProfile>>.value(<_i2.UserProfile>[]),
      ) as _i5.Future<List<_i2.UserProfile>>);

  @override
  void updateToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #updateToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );
}
