// Mocks generated by Mockito 5.4.6 from annotations
// in musicbud_flutter/test/blocs/content/content_bloc_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:musicbud_flutter/domain/repositories/content_repository.dart'
    as _i8;
import 'package:musicbud_flutter/models/album.dart' as _i4;
import 'package:musicbud_flutter/models/artist.dart' as _i3;
import 'package:musicbud_flutter/models/common_anime.dart' as _i6;
import 'package:musicbud_flutter/models/common_manga.dart' as _i7;
import 'package:musicbud_flutter/models/genre.dart' as _i5;
import 'package:musicbud_flutter/models/spotify_device.dart' as _i10;
import 'package:musicbud_flutter/models/track.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTrack_0 extends _i1.SmartFake implements _i2.Track {
  _FakeTrack_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArtist_1 extends _i1.SmartFake implements _i3.Artist {
  _FakeArtist_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlbum_2 extends _i1.SmartFake implements _i4.Album {
  _FakeAlbum_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenre_3 extends _i1.SmartFake implements _i5.Genre {
  _FakeGenre_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommonAnime_4 extends _i1.SmartFake implements _i6.CommonAnime {
  _FakeCommonAnime_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommonManga_5 extends _i1.SmartFake implements _i7.CommonManga {
  _FakeCommonManga_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ContentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentRepository extends _i1.Mock implements _i8.ContentRepository {
  MockContentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i2.Track>> getPlayedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracks,
          [],
        ),
        returnValue: _i9.Future<List<_i2.Track>>.value(<_i2.Track>[]),
      ) as _i9.Future<List<_i2.Track>>);

  @override
  _i9.Future<List<_i2.Track>> getPlayedTracksWithLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracksWithLocation,
          [],
        ),
        returnValue: _i9.Future<List<_i2.Track>>.value(<_i2.Track>[]),
      ) as _i9.Future<List<_i2.Track>>);

  @override
  _i9.Future<List<_i10.SpotifyDevice>> getSpotifyDevices() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpotifyDevices,
          [],
        ),
        returnValue:
            _i9.Future<List<_i10.SpotifyDevice>>.value(<_i10.SpotifyDevice>[]),
      ) as _i9.Future<List<_i10.SpotifyDevice>>);

  @override
  _i9.Future<void> controlSpotifyPlayback(
    String? command,
    String? deviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #controlSpotifyPlayback,
          [
            command,
            deviceId,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setSpotifyVolume(
    String? deviceId,
    int? volume,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSpotifyVolume,
          [
            deviceId,
            volume,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> saveTrackLocation(
    String? trackId,
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTrackLocation,
          [
            trackId,
            latitude,
            longitude,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> playTrack(
    String? trackId,
    String? deviceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #playTrack,
          [
            trackId,
            deviceId,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> playTrackWithLocation(
    String? trackId,
    String? trackName,
    double? latitude,
    double? longitude, [
    String? deviceId,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playTrackWithLocation,
          [
            trackId,
            trackName,
            latitude,
            longitude,
            deviceId,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> savePlayedTrack(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #savePlayedTrack,
          [trackId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.Track>> getPopularTracks() => (super.noSuchMethod(
        Invocation.method(
          #getPopularTracks,
          [],
        ),
        returnValue: _i9.Future<List<_i2.Track>>.value(<_i2.Track>[]),
      ) as _i9.Future<List<_i2.Track>>);

  @override
  _i9.Future<List<_i3.Artist>> getPopularArtists() => (super.noSuchMethod(
        Invocation.method(
          #getPopularArtists,
          [],
        ),
        returnValue: _i9.Future<List<_i3.Artist>>.value(<_i3.Artist>[]),
      ) as _i9.Future<List<_i3.Artist>>);

  @override
  _i9.Future<List<_i4.Album>> getPopularAlbums() => (super.noSuchMethod(
        Invocation.method(
          #getPopularAlbums,
          [],
        ),
        returnValue: _i9.Future<List<_i4.Album>>.value(<_i4.Album>[]),
      ) as _i9.Future<List<_i4.Album>>);

  @override
  _i9.Future<List<_i6.CommonAnime>> getPopularAnime() => (super.noSuchMethod(
        Invocation.method(
          #getPopularAnime,
          [],
        ),
        returnValue:
            _i9.Future<List<_i6.CommonAnime>>.value(<_i6.CommonAnime>[]),
      ) as _i9.Future<List<_i6.CommonAnime>>);

  @override
  _i9.Future<List<_i7.CommonManga>> getPopularManga() => (super.noSuchMethod(
        Invocation.method(
          #getPopularManga,
          [],
        ),
        returnValue:
            _i9.Future<List<_i7.CommonManga>>.value(<_i7.CommonManga>[]),
      ) as _i9.Future<List<_i7.CommonManga>>);

  @override
  _i9.Future<List<_i2.Track>> getTopTracks() => (super.noSuchMethod(
        Invocation.method(
          #getTopTracks,
          [],
        ),
        returnValue: _i9.Future<List<_i2.Track>>.value(<_i2.Track>[]),
      ) as _i9.Future<List<_i2.Track>>);

  @override
  _i9.Future<List<_i3.Artist>> getTopArtists() => (super.noSuchMethod(
        Invocation.method(
          #getTopArtists,
          [],
        ),
        returnValue: _i9.Future<List<_i3.Artist>>.value(<_i3.Artist>[]),
      ) as _i9.Future<List<_i3.Artist>>);

  @override
  _i9.Future<List<_i5.Genre>> getTopGenres() => (super.noSuchMethod(
        Invocation.method(
          #getTopGenres,
          [],
        ),
        returnValue: _i9.Future<List<_i5.Genre>>.value(<_i5.Genre>[]),
      ) as _i9.Future<List<_i5.Genre>>);

  @override
  _i9.Future<List<_i6.CommonAnime>> getTopAnime() => (super.noSuchMethod(
        Invocation.method(
          #getTopAnime,
          [],
        ),
        returnValue:
            _i9.Future<List<_i6.CommonAnime>>.value(<_i6.CommonAnime>[]),
      ) as _i9.Future<List<_i6.CommonAnime>>);

  @override
  _i9.Future<List<_i7.CommonManga>> getTopManga() => (super.noSuchMethod(
        Invocation.method(
          #getTopManga,
          [],
        ),
        returnValue:
            _i9.Future<List<_i7.CommonManga>>.value(<_i7.CommonManga>[]),
      ) as _i9.Future<List<_i7.CommonManga>>);

  @override
  _i9.Future<List<_i2.Track>> getLikedTracks() => (super.noSuchMethod(
        Invocation.method(
          #getLikedTracks,
          [],
        ),
        returnValue: _i9.Future<List<_i2.Track>>.value(<_i2.Track>[]),
      ) as _i9.Future<List<_i2.Track>>);

  @override
  _i9.Future<List<_i3.Artist>> getLikedArtists() => (super.noSuchMethod(
        Invocation.method(
          #getLikedArtists,
          [],
        ),
        returnValue: _i9.Future<List<_i3.Artist>>.value(<_i3.Artist>[]),
      ) as _i9.Future<List<_i3.Artist>>);

  @override
  _i9.Future<List<_i4.Album>> getLikedAlbums() => (super.noSuchMethod(
        Invocation.method(
          #getLikedAlbums,
          [],
        ),
        returnValue: _i9.Future<List<_i4.Album>>.value(<_i4.Album>[]),
      ) as _i9.Future<List<_i4.Album>>);

  @override
  _i9.Future<List<_i5.Genre>> getLikedGenres() => (super.noSuchMethod(
        Invocation.method(
          #getLikedGenres,
          [],
        ),
        returnValue: _i9.Future<List<_i5.Genre>>.value(<_i5.Genre>[]),
      ) as _i9.Future<List<_i5.Genre>>);

  @override
  _i9.Future<void> likeTrack(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #likeTrack,
          [trackId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> unlikeTrack(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeTrack,
          [trackId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> likeArtist(String? artistId) => (super.noSuchMethod(
        Invocation.method(
          #likeArtist,
          [artistId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> unlikeArtist(String? artistId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeArtist,
          [artistId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> likeAlbum(String? albumId) => (super.noSuchMethod(
        Invocation.method(
          #likeAlbum,
          [albumId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> unlikeAlbum(String? albumId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeAlbum,
          [albumId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> likeGenre(String? genreId) => (super.noSuchMethod(
        Invocation.method(
          #likeGenre,
          [genreId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> unlikeGenre(String? genreId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeGenre,
          [genreId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> likeAnime(String? animeId) => (super.noSuchMethod(
        Invocation.method(
          #likeAnime,
          [animeId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> unlikeAnime(String? animeId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeAnime,
          [animeId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> likeManga(String? mangaId) => (super.noSuchMethod(
        Invocation.method(
          #likeManga,
          [mangaId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> unlikeManga(String? mangaId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeManga,
          [mangaId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.Track>> searchTracks(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTracks,
          [query],
        ),
        returnValue: _i9.Future<List<_i2.Track>>.value(<_i2.Track>[]),
      ) as _i9.Future<List<_i2.Track>>);

  @override
  _i9.Future<List<_i3.Artist>> searchArtists(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchArtists,
          [query],
        ),
        returnValue: _i9.Future<List<_i3.Artist>>.value(<_i3.Artist>[]),
      ) as _i9.Future<List<_i3.Artist>>);

  @override
  _i9.Future<List<_i4.Album>> searchAlbums(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchAlbums,
          [query],
        ),
        returnValue: _i9.Future<List<_i4.Album>>.value(<_i4.Album>[]),
      ) as _i9.Future<List<_i4.Album>>);

  @override
  _i9.Future<List<_i5.Genre>> searchGenres(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchGenres,
          [query],
        ),
        returnValue: _i9.Future<List<_i5.Genre>>.value(<_i5.Genre>[]),
      ) as _i9.Future<List<_i5.Genre>>);

  @override
  _i9.Future<List<_i6.CommonAnime>> searchAnime(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchAnime,
          [query],
        ),
        returnValue:
            _i9.Future<List<_i6.CommonAnime>>.value(<_i6.CommonAnime>[]),
      ) as _i9.Future<List<_i6.CommonAnime>>);

  @override
  _i9.Future<List<_i7.CommonManga>> searchManga(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchManga,
          [query],
        ),
        returnValue:
            _i9.Future<List<_i7.CommonManga>>.value(<_i7.CommonManga>[]),
      ) as _i9.Future<List<_i7.CommonManga>>);

  @override
  _i9.Future<_i2.Track> getTrackDetails(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #getTrackDetails,
          [trackId],
        ),
        returnValue: _i9.Future<_i2.Track>.value(_FakeTrack_0(
          this,
          Invocation.method(
            #getTrackDetails,
            [trackId],
          ),
        )),
      ) as _i9.Future<_i2.Track>);

  @override
  _i9.Future<_i3.Artist> getArtistDetails(String? artistId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArtistDetails,
          [artistId],
        ),
        returnValue: _i9.Future<_i3.Artist>.value(_FakeArtist_1(
          this,
          Invocation.method(
            #getArtistDetails,
            [artistId],
          ),
        )),
      ) as _i9.Future<_i3.Artist>);

  @override
  _i9.Future<_i4.Album> getAlbumDetails(String? albumId) => (super.noSuchMethod(
        Invocation.method(
          #getAlbumDetails,
          [albumId],
        ),
        returnValue: _i9.Future<_i4.Album>.value(_FakeAlbum_2(
          this,
          Invocation.method(
            #getAlbumDetails,
            [albumId],
          ),
        )),
      ) as _i9.Future<_i4.Album>);

  @override
  _i9.Future<_i5.Genre> getGenreDetails(String? genreId) => (super.noSuchMethod(
        Invocation.method(
          #getGenreDetails,
          [genreId],
        ),
        returnValue: _i9.Future<_i5.Genre>.value(_FakeGenre_3(
          this,
          Invocation.method(
            #getGenreDetails,
            [genreId],
          ),
        )),
      ) as _i9.Future<_i5.Genre>);

  @override
  _i9.Future<_i6.CommonAnime> getAnimeDetails(String? animeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnimeDetails,
          [animeId],
        ),
        returnValue: _i9.Future<_i6.CommonAnime>.value(_FakeCommonAnime_4(
          this,
          Invocation.method(
            #getAnimeDetails,
            [animeId],
          ),
        )),
      ) as _i9.Future<_i6.CommonAnime>);

  @override
  _i9.Future<_i7.CommonManga> getMangaDetails(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMangaDetails,
          [mangaId],
        ),
        returnValue: _i9.Future<_i7.CommonManga>.value(_FakeCommonManga_5(
          this,
          Invocation.method(
            #getMangaDetails,
            [mangaId],
          ),
        )),
      ) as _i9.Future<_i7.CommonManga>);

  @override
  _i9.Future<List<dynamic>> getTopItems(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopItems,
          [category],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<List<dynamic>> getLikedItems(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedItems,
          [category],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<void> toggleTrackLike(String? trackId) => (super.noSuchMethod(
        Invocation.method(
          #toggleTrackLike,
          [trackId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> toggleArtistLike(String? artistId) => (super.noSuchMethod(
        Invocation.method(
          #toggleArtistLike,
          [artistId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> toggleAlbumLike(String? albumId) => (super.noSuchMethod(
        Invocation.method(
          #toggleAlbumLike,
          [albumId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> toggleGenreLike(String? genreId) => (super.noSuchMethod(
        Invocation.method(
          #toggleGenreLike,
          [genreId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> toggleAnimeLike(String? animeId) => (super.noSuchMethod(
        Invocation.method(
          #toggleAnimeLike,
          [animeId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> toggleMangaLike(String? mangaId) => (super.noSuchMethod(
        Invocation.method(
          #toggleMangaLike,
          [mangaId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateLikes(
    String? type,
    String? id,
    bool? isLiked,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLikes,
          [
            type,
            id,
            isLiked,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> toggleLike(
    String? id,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLike,
          [
            id,
            type,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> playTrackOnService(
    String? trackIdentifier, {
    String? service,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playTrackOnService,
          [trackIdentifier],
          {#service: service},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> createPlaylist({
    required String? name,
    String? description,
    bool? isPrivate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPlaylist,
          [],
          {
            #name: name,
            #description: description,
            #isPrivate: isPrivate,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deletePlaylist(String? playlistId) => (super.noSuchMethod(
        Invocation.method(
          #deletePlaylist,
          [playlistId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updatePlaylist(
    String? playlistId, {
    String? name,
    String? description,
    bool? isPublic,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlaylist,
          [playlistId],
          {
            #name: name,
            #description: description,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> addTrackToPlaylist(
    String? playlistId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTrackToPlaylist,
          [
            playlistId,
            trackId,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> removeTrackFromPlaylist(
    String? playlistId,
    String? trackId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTrackFromPlaylist,
          [
            playlistId,
            trackId,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}
