// Mocks generated by Mockito 5.4.6 from annotations
// in musicbud_flutter/test/integration/app_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:musicbud_flutter/data/network/dio_client.dart' as _i7;
import 'package:musicbud_flutter/data/providers/token_provider.dart' as _i17;
import 'package:musicbud_flutter/domain/repositories/auth_repository.dart'
    as _i16;
import 'package:musicbud_flutter/models/auth_response.dart' as _i4;
import 'package:musicbud_flutter/models/bud_match.dart' as _i12;
import 'package:musicbud_flutter/models/categorized_common_items.dart' as _i15;
import 'package:musicbud_flutter/models/common_album.dart' as _i11;
import 'package:musicbud_flutter/models/common_artist.dart' as _i10;
import 'package:musicbud_flutter/models/common_genre.dart' as _i13;
import 'package:musicbud_flutter/models/common_item.dart' as _i14;
import 'package:musicbud_flutter/models/common_track.dart' as _i9;
import 'package:musicbud_flutter/models/user_profile.dart' as _i3;
import 'package:musicbud_flutter/services/api_service.dart' as _i5;
import 'package:musicbud_flutter/services/dynamic_config_service.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_1 extends _i1.SmartFake implements _i3.UserProfile {
  _FakeUserProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_2<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponse_3 extends _i1.SmartFake implements _i4.LoginResponse {
  _FakeLoginResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterResponse_4 extends _i1.SmartFake
    implements _i4.RegisterResponse {
  _FakeRegisterResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTokenRefreshResponse_5 extends _i1.SmartFake
    implements _i4.TokenRefreshResponse {
  _FakeTokenRefreshResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  void setDioClientForTesting(_i7.DioClient? dioClient) => super.noSuchMethod(
        Invocation.method(
          #setDioClientForTesting,
          [dioClient],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> initialize(String? baseUrl) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [baseUrl],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> fetchCsrfToken() => (super.noSuchMethod(
        Invocation.method(
          #fetchCsrfToken,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setLoggedIn(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setLoggedIn,
          [value],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.UserProfile> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i8.Future<_i3.UserProfile>.value(_FakeUserProfile_1(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i8.Future<_i3.UserProfile>);

  @override
  _i8.Future<String> connectService(String? service) => (super.noSuchMethod(
        Invocation.method(
          #connectService,
          [service],
        ),
        returnValue: _i8.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #connectService,
            [service],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<List<_i9.CommonTrack>> getTopTracks({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopTracks,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<List<_i9.CommonTrack>>.value(<_i9.CommonTrack>[]),
      ) as _i8.Future<List<_i9.CommonTrack>>);

  @override
  _i8.Future<List<_i10.CommonArtist>> getTopArtists({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopArtists,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<List<_i10.CommonArtist>>.value(<_i10.CommonArtist>[]),
      ) as _i8.Future<List<_i10.CommonArtist>>);

  @override
  _i8.Future<List<String>> getTopGenres({int? page = 1}) => (super.noSuchMethod(
        Invocation.method(
          #getTopGenres,
          [],
          {#page: page},
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<List<_i11.CommonAlbum>> getLikedAlbums({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedAlbums,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<List<_i11.CommonAlbum>>.value(<_i11.CommonAlbum>[]),
      ) as _i8.Future<List<_i11.CommonAlbum>>);

  @override
  _i8.Future<List<_i9.CommonTrack>> getPlayedTracks({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracks,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<List<_i9.CommonTrack>>.value(<_i9.CommonTrack>[]),
      ) as _i8.Future<List<_i9.CommonTrack>>);

  @override
  _i8.Future<List<_i12.BudMatch>> getTopArtistsBuds({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopArtistsBuds,
          [],
          {#page: page},
        ),
        returnValue: _i8.Future<List<_i12.BudMatch>>.value(<_i12.BudMatch>[]),
      ) as _i8.Future<List<_i12.BudMatch>>);

  @override
  _i8.Future<List<_i12.BudMatch>> getTopTracksBuds({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopTracksBuds,
          [],
          {#page: page},
        ),
        returnValue: _i8.Future<List<_i12.BudMatch>>.value(<_i12.BudMatch>[]),
      ) as _i8.Future<List<_i12.BudMatch>>);

  @override
  _i8.Future<List<_i12.BudMatch>> getTopGenresBuds({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopGenresBuds,
          [],
          {#page: page},
        ),
        returnValue: _i8.Future<List<_i12.BudMatch>>.value(<_i12.BudMatch>[]),
      ) as _i8.Future<List<_i12.BudMatch>>);

  @override
  _i8.Future<List<_i12.BudMatch>> getLikedArtistsBuds({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedArtistsBuds,
          [],
          {#page: page},
        ),
        returnValue: _i8.Future<List<_i12.BudMatch>>.value(<_i12.BudMatch>[]),
      ) as _i8.Future<List<_i12.BudMatch>>);

  @override
  _i8.Future<List<_i12.BudMatch>> getLikedTracksBuds({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedTracksBuds,
          [],
          {#page: page},
        ),
        returnValue: _i8.Future<List<_i12.BudMatch>>.value(<_i12.BudMatch>[]),
      ) as _i8.Future<List<_i12.BudMatch>>);

  @override
  _i8.Future<List<_i12.BudMatch>> getLikedAlbumsBuds({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedAlbumsBuds,
          [],
          {#page: page},
        ),
        returnValue: _i8.Future<List<_i12.BudMatch>>.value(<_i12.BudMatch>[]),
      ) as _i8.Future<List<_i12.BudMatch>>);

  @override
  _i8.Future<List<_i12.BudMatch>> getLikedGenresBuds({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedGenresBuds,
          [],
          {#page: page},
        ),
        returnValue: _i8.Future<List<_i12.BudMatch>>.value(<_i12.BudMatch>[]),
      ) as _i8.Future<List<_i12.BudMatch>>);

  @override
  _i8.Future<List<_i12.BudMatch>> getPlayedTracksBuds({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracksBuds,
          [],
          {#page: page},
        ),
        returnValue: _i8.Future<List<_i12.BudMatch>>.value(<_i12.BudMatch>[]),
      ) as _i8.Future<List<_i12.BudMatch>>);

  @override
  _i8.Future<List<_i10.CommonArtist>> getCommonTopArtists(String? budId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonTopArtists,
          [budId],
        ),
        returnValue:
            _i8.Future<List<_i10.CommonArtist>>.value(<_i10.CommonArtist>[]),
      ) as _i8.Future<List<_i10.CommonArtist>>);

  @override
  _i8.Future<List<_i9.CommonTrack>> getCommonTopTracks(String? budId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonTopTracks,
          [budId],
        ),
        returnValue:
            _i8.Future<List<_i9.CommonTrack>>.value(<_i9.CommonTrack>[]),
      ) as _i8.Future<List<_i9.CommonTrack>>);

  @override
  _i8.Future<List<_i13.CommonGenre>> getCommonTopGenres(String? budId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonTopGenres,
          [budId],
        ),
        returnValue:
            _i8.Future<List<_i13.CommonGenre>>.value(<_i13.CommonGenre>[]),
      ) as _i8.Future<List<_i13.CommonGenre>>);

  @override
  _i8.Future<List<_i10.CommonArtist>> getCommonLikedArtists(String? budId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonLikedArtists,
          [budId],
        ),
        returnValue:
            _i8.Future<List<_i10.CommonArtist>>.value(<_i10.CommonArtist>[]),
      ) as _i8.Future<List<_i10.CommonArtist>>);

  @override
  _i8.Future<List<_i9.CommonTrack>> getCommonLikedTracks(String? budId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonLikedTracks,
          [budId],
        ),
        returnValue:
            _i8.Future<List<_i9.CommonTrack>>.value(<_i9.CommonTrack>[]),
      ) as _i8.Future<List<_i9.CommonTrack>>);

  @override
  _i8.Future<List<_i13.CommonGenre>> getCommonLikedGenres(String? budId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonLikedGenres,
          [budId],
        ),
        returnValue:
            _i8.Future<List<_i13.CommonGenre>>.value(<_i13.CommonGenre>[]),
      ) as _i8.Future<List<_i13.CommonGenre>>);

  @override
  _i8.Future<List<_i11.CommonAlbum>> getCommonLikedAlbums(String? budId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonLikedAlbums,
          [budId],
        ),
        returnValue:
            _i8.Future<List<_i11.CommonAlbum>>.value(<_i11.CommonAlbum>[]),
      ) as _i8.Future<List<_i11.CommonAlbum>>);

  @override
  _i8.Future<List<_i12.BudMatch>> getBuds(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBuds,
          [category],
        ),
        returnValue: _i8.Future<List<_i12.BudMatch>>.value(<_i12.BudMatch>[]),
      ) as _i8.Future<List<_i12.BudMatch>>);

  @override
  _i8.Future<List<String>> getAvailableBudCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableBudCategories,
          [],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<List<_i12.BudMatch>> getTopBuds() => (super.noSuchMethod(
        Invocation.method(
          #getTopBuds,
          [],
        ),
        returnValue: _i8.Future<List<_i12.BudMatch>>.value(<_i12.BudMatch>[]),
      ) as _i8.Future<List<_i12.BudMatch>>);

  @override
  _i8.Future<List<_i14.CommonItem>> getCommonItems(
    String? budId,
    String? endpoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonItems,
          [
            budId,
            endpoint,
          ],
        ),
        returnValue:
            _i8.Future<List<_i14.CommonItem>>.value(<_i14.CommonItem>[]),
      ) as _i8.Future<List<_i14.CommonItem>>);

  @override
  _i8.Future<List<_i15.CategorizedCommonItems>> getAllCommonItems(
          String? budId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCommonItems,
          [budId],
        ),
        returnValue: _i8.Future<List<_i15.CategorizedCommonItems>>.value(
            <_i15.CategorizedCommonItems>[]),
      ) as _i8.Future<List<_i15.CategorizedCommonItems>>);

  @override
  _i8.Future<Map<String, dynamic>> register(
    String? username,
    String? password,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            username,
            password,
            email,
          ],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  bool isTokenExpired() => (super.noSuchMethod(
        Invocation.method(
          #isTokenExpired,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<_i3.UserProfile> updateUserProfile(
          Map<String, dynamic>? updatedData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [updatedData],
        ),
        returnValue: _i8.Future<_i3.UserProfile>.value(_FakeUserProfile_1(
          this,
          Invocation.method(
            #updateUserProfile,
            [updatedData],
          ),
        )),
      ) as _i8.Future<_i3.UserProfile>);

  @override
  _i8.Future<List<T>> fetchItems<T>(
    String? endpoint, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchItems,
          [endpoint],
          {#page: page},
        ),
        returnValue: _i8.Future<List<T>>.value(<T>[]),
      ) as _i8.Future<List<T>>);

  @override
  _i8.Future<String?> uploadProfilePhoto(String? imagePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfilePhoto,
          [imagePath],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<List<_i9.CommonTrack>> getCommonTracks(String? budUid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonTracks,
          [budUid],
        ),
        returnValue:
            _i8.Future<List<_i9.CommonTrack>>.value(<_i9.CommonTrack>[]),
      ) as _i8.Future<List<_i9.CommonTrack>>);

  @override
  _i8.Future<List<_i10.CommonArtist>> getCommonArtists(String? budUid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonArtists,
          [budUid],
        ),
        returnValue:
            _i8.Future<List<_i10.CommonArtist>>.value(<_i10.CommonArtist>[]),
      ) as _i8.Future<List<_i10.CommonArtist>>);

  @override
  _i8.Future<List<_i13.CommonGenre>> getCommonGenres(String? budUid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonGenres,
          [budUid],
        ),
        returnValue:
            _i8.Future<List<_i13.CommonGenre>>.value(<_i13.CommonGenre>[]),
      ) as _i8.Future<List<_i13.CommonGenre>>);

  @override
  _i8.Future<List<_i9.CommonTrack>> getCommonPlayedTracks(
    String? budUid, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommonPlayedTracks,
          [budUid],
          {#page: page},
        ),
        returnValue:
            _i8.Future<List<_i9.CommonTrack>>.value(<_i9.CommonTrack>[]),
      ) as _i8.Future<List<_i9.CommonTrack>>);

  @override
  _i8.Future<void> testApiConnection() => (super.noSuchMethod(
        Invocation.method(
          #testApiConnection,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> createChannel(String? channelName) => (super.noSuchMethod(
        Invocation.method(
          #createChannel,
          [channelName],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> checkServerConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkServerConnectivity,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> saveLocation(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocation,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playTrackWithLocation(
    String? trackUid,
    String? trackName,
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #playTrackWithLocation,
          [
            trackUid,
            trackName,
            latitude,
            longitude,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> likeItem(
    String? itemType,
    String? itemId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #likeItem,
          [
            itemType,
            itemId,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> unlikeItem(
    String? itemType,
    String? itemId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlikeItem,
          [
            itemType,
            itemId,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<List<_i9.CommonTrack>> getCurrentlyPlayedTracks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentlyPlayedTracks,
          [],
        ),
        returnValue:
            _i8.Future<List<_i9.CommonTrack>>.value(<_i9.CommonTrack>[]),
      ) as _i8.Future<List<_i9.CommonTrack>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getSpotifyDevices() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpotifyDevices,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<bool> playSpotifyTrack(
    String? trackId, {
    String? deviceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playSpotifyTrack,
          [trackId],
          {#deviceId: deviceId},
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<List<_i9.CommonTrack>> getPlayedTracksWithLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayedTracksWithLocation,
          [],
        ),
        returnValue:
            _i8.Future<List<_i9.CommonTrack>>.value(<_i9.CommonTrack>[]),
      ) as _i8.Future<List<_i9.CommonTrack>>);

  @override
  _i8.Future<bool> checkInternetConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #checkInternetConnectivity,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  void logDioConfiguration() => super.noSuchMethod(
        Invocation.method(
          #logDioConfiguration,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> setAuthToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setRefreshToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setRefreshToken,
          [token],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> shouldRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #shouldRefreshToken,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i2.Response<dynamic>> retry(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #retry,
          [requestOptions],
        ),
        returnValue:
            _i8.Future<_i2.Response<dynamic>>.value(_FakeResponse_2<dynamic>(
          this,
          Invocation.method(
            #retry,
            [requestOptions],
          ),
        )),
      ) as _i8.Future<_i2.Response<dynamic>>);

  @override
  _i8.Future<void> updateTokens(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTokens,
          [data],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> handleSpotifyToken(String? spotifyToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleSpotifyToken,
          [spotifyToken],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> handleYtMusicToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleYtMusicToken,
          [token],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> handleLastFmToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleLastFmToken,
          [token],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> handleMalToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleMalToken,
          [token],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> updateLikes(String? serviceName) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLikes,
          [serviceName],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<List<dynamic>> getBudsByTrack(String? trackId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByTrack,
          [trackId],
        ),
        returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<List<dynamic>> getBudsByArtist(String? artistId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByArtist,
          [artistId],
        ),
        returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<List<dynamic>> getBudsByGenre(String? genreId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByGenre,
          [genreId],
        ),
        returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<void> playTrack(
    String? trackIdentifier, {
    String? service,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playTrack,
          [trackIdentifier],
          {#service: service},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> getBudProfile(String? budId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudProfile,
          [budId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getBudsByTopArtists({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByTopArtists,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getBudsByTopTracks({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByTopTracks,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getBudsByTopGenres({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByTopGenres,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getBudsByLikedArtists({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByLikedArtists,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getBudsByLikedTracks({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByLikedTracks,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getBudsByLikedGenres({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByLikedGenres,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getBudsByLikedAlbums({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByLikedAlbums,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getBudsByLikedAio({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByLikedAio,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getBudsByTopAnime({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByTopAnime,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getBudsByTopManga({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBudsByTopManga,
          [],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i16.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.LoginResponse> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue: _i8.Future<_i4.LoginResponse>.value(_FakeLoginResponse_3(
          this,
          Invocation.method(
            #login,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i8.Future<_i4.LoginResponse>);

  @override
  _i8.Future<_i4.RegisterResponse> register(
    String? username,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            username,
            email,
            password,
          ],
        ),
        returnValue:
            _i8.Future<_i4.RegisterResponse>.value(_FakeRegisterResponse_4(
          this,
          Invocation.method(
            #register,
            [
              username,
              email,
              password,
            ],
          ),
        )),
      ) as _i8.Future<_i4.RegisterResponse>);

  @override
  _i8.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i4.TokenRefreshResponse> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i8.Future<_i4.TokenRefreshResponse>.value(
            _FakeTokenRefreshResponse_5(
          this,
          Invocation.method(
            #refreshToken,
            [],
          ),
        )),
      ) as _i8.Future<_i4.TokenRefreshResponse>);

  @override
  _i8.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> getServiceAuthUrl() => (super.noSuchMethod(
        Invocation.method(
          #getServiceAuthUrl,
          [],
        ),
        returnValue: _i8.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getServiceAuthUrl,
            [],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String> getServiceLoginUrl(String? service) => (super.noSuchMethod(
        Invocation.method(
          #getServiceLoginUrl,
          [service],
        ),
        returnValue: _i8.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getServiceLoginUrl,
            [service],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> connectSpotify(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectSpotify,
          [code],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> connectYTMusic(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectYTMusic,
          [code],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> connectLastFM(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectLastFM,
          [code],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> connectMAL(String? code) => (super.noSuchMethod(
        Invocation.method(
          #connectMAL,
          [code],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> refreshSpotifyToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshSpotifyToken,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> refreshYTMusicToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshYTMusicToken,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [TokenProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenProvider extends _i1.Mock implements _i17.TokenProvider {
  MockTokenProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateAccessToken(String? newToken) => (super.noSuchMethod(
        Invocation.method(
          #updateAccessToken,
          [newToken],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateToken(String? newToken) => (super.noSuchMethod(
        Invocation.method(
          #updateToken,
          [newToken],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearToken() => (super.noSuchMethod(
        Invocation.method(
          #clearToken,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [DynamicConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDynamicConfigService extends _i1.Mock
    implements _i18.DynamicConfigService {
  MockDynamicConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  T get<T>(
    String? key, {
    T? defaultValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValue: _i6.dummyValue<T>(
          this,
          Invocation.method(
            #get,
            [key],
            {#defaultValue: defaultValue},
          ),
        ),
      ) as T);

  @override
  _i8.Future<void> set<T>(
    String? key,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            key,
            value,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  Map<String, dynamic> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i8.Future<void> update(Map<String, dynamic>? newConfig) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [newConfig],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isFeatureEnabled(String? feature) => (super.noSuchMethod(
        Invocation.method(
          #isFeatureEnabled,
          [feature],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> setFeatureEnabled(
    String? feature,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFeatureEnabled,
          [
            feature,
            enabled,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  String getApiEndpoint() => (super.noSuchMethod(
        Invocation.method(
          #getApiEndpoint,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getApiEndpoint,
            [],
          ),
        ),
      ) as String);

  @override
  String getTheme() => (super.noSuchMethod(
        Invocation.method(
          #getTheme,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTheme,
            [],
          ),
        ),
      ) as String);

  @override
  _i8.Future<void> setTheme(String? theme) => (super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [theme],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  String getLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getLanguage,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguage,
            [],
          ),
        ),
      ) as String);

  @override
  _i8.Future<void> setLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [language],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isAnalyticsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isAnalyticsEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> setAnalyticsEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setAnalyticsEnabled,
          [enabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  int getCacheDuration() => (super.noSuchMethod(
        Invocation.method(
          #getCacheDuration,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i8.Future<void> setCacheDuration(int? duration) => (super.noSuchMethod(
        Invocation.method(
          #setCacheDuration,
          [duration],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  int getTimeout() => (super.noSuchMethod(
        Invocation.method(
          #getTimeout,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i8.Future<void> setTimeout(int? timeout) => (super.noSuchMethod(
        Invocation.method(
          #setTimeout,
          [timeout],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  int getMaxRetries() => (super.noSuchMethod(
        Invocation.method(
          #getMaxRetries,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i8.Future<void> setMaxRetries(int? retries) => (super.noSuchMethod(
        Invocation.method(
          #setMaxRetries,
          [retries],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  Map<String, dynamic> getUiConfig() => (super.noSuchMethod(
        Invocation.method(
          #getUiConfig,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> getPrivacyConfig() => (super.noSuchMethod(
        Invocation.method(
          #getPrivacyConfig,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i8.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
